plugins {
    id 'com.android.application'
}

android {
    namespace 'com.forexpilot.aipro'
    compileSdk 35

    defaultConfig {
        applicationId "com.forexpilot.aipro"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"

        def twelveDataKey = project.findProperty("twelveDataApiKey") ?: ""

        buildConfigField(
                "String",
                "TWELVE_DATA_API_KEY",
                "\"${twelveDataKey}\""
        )
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}