package com.forexpilot.aipro;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Connects:
 *
 * BackgroundScanner
 *       ↓
 * MultiTimeframeEngine
 *       ↓
 * SignalNotificationManager
 *
 * This class is standalone and does not modify MainActivity.
 */
public class SignalAlertCoordinator {

    private static final String[] TIMEFRAMES = {
            "5M",
            "15M",
            "30M",
            "1H",
            "4H",
            "1D"
    };

    private final BackgroundScanner scanner;
    private final MultiTimeframeEngine multiTimeframeEngine;
    private final SignalNotificationManager notificationManager;

    private final Map<String, List<Signal>> signalCache =
            new HashMap<>();

    private String currentMarket = "";

    private boolean enabled = true;

    public SignalAlertCoordinator(
            BackgroundScanner scanner,
            MultiTimeframeEngine multiTimeframeEngine,
            SignalNotificationManager notificationManager
    ) {
        this.scanner = scanner;
        this.multiTimeframeEngine = multiTimeframeEngine;
        this.notificationManager = notificationManager;

        attachScannerCallbacks();
    }

    /**
     * Enables or disables notifications generated by this coordinator.
     */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Returns whether the coordinator is enabled.
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Starts the background scanner.
     */
    public void start() {
        if (scanner != null) {
            scanner.start();
        }
    }

    /**
     * Stops the background scanner.
     */
    public void stop() {
        if (scanner != null) {
            scanner.stop();
        }

        signalCache.clear();
        currentMarket = "";
    }

    /**
     * Requests an immediate scan.
     */
    public void scanNow(String market) {
        if (scanner == null || market == null || market.trim().isEmpty()) {
            return;
        }

        currentMarket = market;
        scanner.scanNow(market);
    }

    /**
     * Changes the market being monitored.
     */
    public void setMarket(String market) {
        if (market == null) {
            currentMarket = "";
            signalCache.clear();
            return;
        }

        String normalized = market.trim();

        if (!normalized.equals(currentMarket)) {
            currentMarket = normalized;
            signalCache.clear();
        }
    }

    /**
     * Returns the currently monitored market.
     */
    public String getCurrentMarket() {
        return currentMarket;
    }

    /**
     * Connects BackgroundScanner callbacks to the MTF engine.
     */
    private void attachScannerCallbacks() {

        scanner.setCallback(new BackgroundScanner.Callback() {

            @Override
            public void onScanStarted() {
                // Scanner has started.
            }

            @Override
            public void onTimeframeResult(
                    String market,
                    String timeframe,
                    Signal signal
            ) {

                if (market == null || timeframe == null || signal == null) {
                    return;
                }

                currentMarket = market;

                List<Signal> signals =
                        signalCache.get(market);

                if (signals == null) {
                    signals = new ArrayList<>();
                    signalCache.put(market, signals);
                }

                replaceTimeframeSignal(
                        signals,
                        timeframe,
                        signal
                );

                evaluateConfluence(
                        market,
                        signals
                );
            }

            @Override
            public void onScanCompleted(
                    String market,
                    List<Signal> signals
            ) {

                if (market == null) {
                    return;
                }

                if (signals != null) {
                    signalCache.put(
                            market,
                            new ArrayList<>(signals)
                    );
                }

                evaluateConfluence(
                        market,
                        signals
                );
            }

            @Override
            public void onScanError(
                    String market,
                    String timeframe,
                    String message
            ) {
                // Do not generate fake signals from errors.
            }
        });
    }

    /**
     * Replaces the cached signal for a specific timeframe.
     */
    private void replaceTimeframeSignal(
            List<Signal> signals,
            String timeframe,
            Signal newSignal
    ) {

        for (int i = 0; i < signals.size(); i++) {

            Signal existing = signals.get(i);

            if (existing != null
                    && timeframe.equalsIgnoreCase(
                    existing.getTimeframe())) {

                signals.set(i, newSignal);
                return;
            }
        }

        signals.add(newSignal);
    }

    /**
     * Converts the collected Signals into the format required by
     * MultiTimeframeEngine and evaluates the confluence.
     */
    private void evaluateConfluence(
            String market,
            List<Signal> signals
    ) {

        if (!enabled || signals == null) {
            return;
        }

        if (signals.size() < TIMEFRAMES.length) {
            return;
        }

        List<MultiTimeframeEngine.TimeframeResult> results =
                new ArrayList<>();

        for (String timeframe : TIMEFRAMES) {

            Signal signal =
                    findSignal(
                            signals,
                            timeframe
                    );

            if (signal == null) {
                return;
            }

            results.add(
                    new MultiTimeframeEngine.TimeframeResult(
                            timeframe,
                            signal.getDirection(),
                            signal.getReason(),
                            signal.getRsi(),
                            signal.getAtr()
                    )
            );
        }

        MultiTimeframeEngine.ConfluenceResult confluence =
                multiTimeframeEngine.calculateConfluence(
                        results
                );

        if (confluence == null) {
            return;
        }

        Signal.Direction direction =
                confluence.getDirection();

        int strength =
                confluence.getStrength();

        /*
         * Existing MultiTimeframeEngine requires at least
         * 4/6 agreement for BUY or SELL confluence.
         *
         * WAIT never produces a notification.
         */
        if (direction == Signal.Direction.WAIT) {
            return;
        }

        if (strength < 4) {
            return;
        }

        Signal notificationSignal =
                selectNotificationSignal(
                        signals,
                        direction
                );

        if (notificationSignal == null) {
            return;
        }

        notificationManager.notifySignal(
                market,
                notificationSignal,
                strength
        );
    }

    /**
     * Finds a signal for a specific timeframe.
     */
    private Signal findSignal(
            List<Signal> signals,
            String timeframe
    ) {

        for (Signal signal : signals) {

            if (signal == null) {
                continue;
            }

            if (timeframe.equalsIgnoreCase(
                    signal.getTimeframe())) {

                return signal;
            }
        }

        return null;
    }

    /**
     * Selects the strongest available BUY/SELL signal that matches
     * the confirmed MTF direction.
     *
     * Preference:
     * 15M → 30M → 5M → 1H → 4H → 1D
     */
    private Signal selectNotificationSignal(
            List<Signal> signals,
            Signal.Direction direction
    ) {

        String[] priority = {
                "15M",
                "30M",
                "5M",
                "1H",
                "4H",
                "1D"
        };

        for (String timeframe : priority) {

            Signal signal =
                    findSignal(
                            signals,
                            timeframe
                    );

            if (signal == null) {
                continue;
            }

            if (signal.getDirection() == direction) {
                return signal;
            }
        }

        return null;
    }

    /**
     * Clears cached signals for a market.
     */
    public void clearMarket(String market) {

        if (market == null) {
            return;
        }

        signalCache.remove(
                market.trim()
        );
    }

    /**
     * Clears all cached signals.
     */
    public void clearAll() {
        signalCache.clear();
    }
}